version: '{build}'
skip_tags: true
image:
  - Ubuntu1804

build_script:
  - sh: sudo ./build.sh

after_build:
  - sh: appveyor PushArtifact chroot.tar.gz -DeploymentName chroot

test: off
deploy:
- provider: GitHub
  tag: continuous-$(APPVEYOR_REPO_BRANCH)
  release: Continuous build
  auth_token:
    secure: LkZ5LQC3CMMNhMwBVpwazXelrJdIPzi57na8aE5AZhCTHL/cOUsHBL6NJ25scFGL
  artifact: chroot
  prerelease: true
  force_update: true
